sudo: required
language: node_js
services:
- docker
node_js:
- 8.11.3
script:
- npm run test
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- echo $AWS_ACCESS_KEY_ID
- echo $AWS_SECRET_ACCESS_KEY
- echo $MY_SECRET_ENV
- eval $(aws ecr get-login --no-include-email --region us-east-2)
- docker build -t express-hello .
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- export HELLO_IMAGE_VERSION=$TRAVIS_COMMIT
- node run generateDeployFile
- sudo curl -o ./ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- chmod +x ./ecs-cli
- "./ecs-cli compose down"
- "./ecs-cli compose up"
env:
  global:
    secure: lybKNmLQyAt9oSEsChEJ7Nd7LgfTw9snbgzNMe94oSDv6w5MmD7zdSx2xJlwBnxODZJUJkpYu14DNTMGnCWLxdefrtMwzEwAW3JiE/qtf/quJGLRAD5eT3v9pIy8p8+6tl/51ZRoYA/Hq7E/sKQLdw7eqV9pD4pet3nv7551w+eS4TYNlWhJvgo8PphOMS/2o1dtEkVZYKKUEazIsstHkqZSzOSqCc5wq7L/teA7qjb7npJOKeLFIHAs/9SfVeJl1OHoUhASLHb57kp2UGL+PuRUzZGZLhehQgwn4au8Rq2u+hmfVsM28w4nGxgB3CFbTAmbdpGW626fVsr9Su52xu0Np1LvVyx0RXjCT0foMA+T+cCGq+SBChM+5SKdhIzdMxWOdFNB7Okh8lggIW+Kh5h3VR9sQSzTZdaqRUMDH5qYq7XM1AUZMU01s1OxUf95mKaMNa+YSRUV5izneirtoGCKJeDSUa9J5Sd8dQgjvbEh66N20YkxdWuJ8QVChayEvP2gAuxUmDfjvWCTg1b3vRVMyQsVFfOZmPwPjI0+dMsWz/4DesnzvslivjGAkoSgsocBbf7fX5LDhGr27WZEDbZIgFMu886ILOhz8TU4C8JOdyWzs8PN9/Rx1lx7yaj0xuaoCCwJ4ZAjTV46+0jsHnxDUQkuojwwkHxsjasx3JM=
