sudo: required
language: node_js
services:
- docker
node_js:
- 8.11.3

addons:
  ssh_known_hosts: ec2-18-188-240-88.us-east-2.compute.amazonaws.com

env:
  global:
    - "ECS_CLUSTER=pruebita-6"
    - "AWS_REGION=ue-east-2"

script:
- npm run test
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- export HELLO_IMAGE_VERSION=$TRAVIS_COMMIT


deploy:
  - provider: script
    script: bash ./deploy/create_docker_image.sh
    on: master
  - provider: script
    script: bash ./deploy/deploy-to-server.sh
    on: master
