sudo: required
language: node_js
env:
  global:
    secure: b/CGw4SXe8WHvD9hdMZcEmOqsAc0xaM3t5hCjq+haeLNifgCbU00TWsnChQu4tKMHtCr1RKl59wZl8H/qKuPqH7b2eh4kylp/XDUN4iXYTGQWbTdId7Ma41dd6W/4JirJZF1xP/UN3TKS2RmJ3lF2W8+rJms941kmi5alxCbLIYewBNnnRZdcMHXDqprrjbali/jUNLab7d2fxWGyr+fLi4qS9e4ICG0nFbw1+goQsQY5dIY+bzI/fq/AmPUaYl70bnC9JfY1T9oUWYxMqUjPEcMf0uROFhpmj79le9JtbjBzsoIaTAcouBtdMMnMFUfEmOZj+SjDyFCuR6jEXwZRYnBsTSTwPTAy0ujY78/0ZWOKLG/b6f+/VKMAMXO+SFzkt1fbsXZCkOdesEpcOmvikzol7i0oaKzb3c7JaKXZinwqsHWCW3oIuNrq1JFZorg46l+sCUby7pacae6HUupNEM7Jped1uk9/k+PhmFzLgxVFVEoVk5208LjUlt6kEcZz+Il+ayw59zLqNuE0aXjQG1ip9OMUGQnjkYKQJiJRyK58v4FTZ8hi88jD3FiOQkmXi2EUDYRV9zZHahZ/Y0hCIB+CkqvnmTgtkhkLSGa+afUOirN7uiBgzKT02hYFIx3f8sSYN/LwWdkVxqTr/KbJMtIWYIpRfs20GXmgAHa5p0=
services:
- docker
node_js:
- 8.11.3
script:
- npm run test
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- echo $AWS_ACCESS_KEY_ID
- echo $AWS_SECRET_ACCESS_KEY
- echo $MY_SECRET_ENV
- eval $(aws ecr get-login --no-include-email --region us-east-2)
- docker build -t express-hello .
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- export HELLO_IMAGE_VERSION=$TRAVIS_COMMIT
- node run generateDeployFile
- sudo curl -o ./ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- chmod +x ./ecs-cli
- "./ecs-cli compose down"
- "./ecs-cli compose up"
