sudo: required
language: node_js
services:
- docker
node_js:
- 8.11.3
script:
- npm run test
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- echo $AWS_ACCESS_KEY_ID
- echo $AWS_SECRET_ACCESS_KEY
- echo $qopnEDEMr0
- eval $(aws ecr get-login --no-include-email --region us-east-2)
- docker build -t express-hello .
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- export HELLO_IMAGE_VERSION=$TRAVIS_COMMIT
- npm run generateDeployFile
- sudo curl -o ./ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x ./ecs-cli
- "./ecs-cli compose down"
- "./ecs-cli compose up"
env:
  global:
    - "ECS_CLUSTER=pruebita-6"
    - "AWS_REGION=ue-east-2"
