sudo: required
language: node_js
services:
- docker
node_js:
- 8.11.3
script:
- npm run test
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- echo $AWS_ACCESS_KEY_ID
- echo $AWS_SECRET_ACCESS_KEY
- echo $FOO
- eval $(aws ecr get-login --no-include-email --region us-east-2)
- docker build -t express-hello .
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- export HELLO_IMAGE_VERSION=$TRAVIS_COMMIT
- node run generateDeployFile
- sudo curl -o ./ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- chmod +x ./ecs-cli
- "./ecs-cli compose down"
- "./ecs-cli compose up"
env:
  global:
    secure: DL5oMLYBjS7gVCcjPKi0iH8tROuMA8PUhWMLEGni87xE+fNUAS4wuWy+oPDQoA+hilIR4Kvv9PaKpZv7vFpQAFQ//4BOWgHJFEI8kBQysywjuI5ajLTwpm0PUnQtUj/rDNtspevNxvvbLy0bXvXMEYcuKovyVU+EvHlRbbgdd/cxkwkfQMOwuHb00C3lP/dGy4CDRkucoDeCxYy8vRRwbDPdas7kkeEiEq8WAHQF+PmEv1TbW8ohXEimMnXBYIZzgViwFUkjqxp2ywFhmGTwNMoMjWBtV+bTgKQuSLwRrUZHz05K3pZVjK/He6ucFb+EZs8NU/pCw0Z2UpddaSRTo4E4tdEfS8nrfZnIlC/Z7/G7PR4s3zByoEb7KmBpYUk5kk8PGyIl7qXxInAgEqU85RCAclZhJJkledZha9o6TE+TGV2RJs1RxcwDots9DKii0aWl26Ce5u49BrC8WVzVDPHgSydXAEDZ1zD7T8YLQHLMAm25i7STLfj0GvXQFTYUGdY9+Ly7PlUWAy4+odjRMh89DwBc/M5HdZPYUPPSS3VDcz9EN4bHUmH2b/C/CchbfczKtVkD3xX5xGV2A+GMP+84wWTHR5KLrzEdFO8XiuqmkNtkw5br4pDbiMQvcDnVmOm6gZDVpt2uurb6OkLVEZ7nM+tArJkokK8qmw24E60=
