sudo: required
language: node_js
services:
- docker
node_js:
- 8.11.3
script:
- npm run test
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- echo $AWS_ACCESS_KEY_ID
- echo $AWS_SECRET_ACCESS_KEY
- echo $FOO
- eval $(aws ecr get-login --no-include-email --region us-east-2)
- docker build -t express-hello .
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- export HELLO_IMAGE_VERSION=$TRAVIS_COMMIT
- node run generateDeployFile
- sudo curl -o ./ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- chmod +x ./ecs-cli
- "./ecs-cli compose down"
- "./ecs-cli compose up"
env:
  global:
  - secure: "1YrjIGESPOCcpMfOaroSSsJxhW+WWmTq1ejwaskHaYZsB9Ejtw2yOKLs18trNJWvhIOEbbDpp/raHBD8HMzojlN+WRPDz5XfB9sBY1w7ZWyynUEpcp+9f8LW0sr48dOvxQtMc+HMUm6fxBamLXVMyYlZ09RqLlpQ8xE/BnEROkiGa7ZV2wzQKJu6Tx9MrCm4AEpIY6xyWkuSCpuMmJV7oYRj7FzRNY2qX0hFjFsPpnR/b8/rx9YbJ/RgeBp1G9YP2S4KDND2YwKoaB5jBwjxmVW42aqp/m0biBKJzws8tWqKqg8OuIbLBvt1lHEiFjXz5B0URfHaZo95Fv044ogam5X+Hd3Fphu6Pf6ywm6hch24TSSbeYrZiH1Qn3k+bWhxp8UGWzDJsIYoAdWLLu88iQ1T4trK10V1jdi+NuDfYX7chemGnexlCjFiIxur9ecuhidwNlKg3WF7DqpVf5Lf3fMdSDEoFb2YFWbu/YKlnx7LOqoC8pJrBI0Pf0uXsDc8Iy5a7MrYbxHW5YXYHUZDEXP5PbBp6tf9fgQnX6GCwujzT4o7nh4zVY0afYHb23HubTgXWY58Rn25twBuR6dJ6J92jGNIblRApwZG3DOwB309UMuEFs+D2lOQLmCZVPcytoGHe9S44Bt6cWGWBDSId7gDK4jRSXw0/qopnEDEMr0="
  - secure: "BkLIEdcFxlTHssKOrRgW6IABWdm9pzUpqqpDQDOx4kYii0QyMlvI4zGsKDEgScElbuHLaxHqEZTme0x3VZdoN8DEnm9yK0y5M4vUxgSRCD2Az8c4wpmT5XGdS44Gr+9s8a0g0LJR3/Lhu5fnxk9vsD3TRnyIgp3wWze/UF+OdIkZ3cAnp8Xi7i4wr019A7rFOh6u6K0iB9IY4dvAlnqv8/8eEWcdDnC6f1d2B0bhu42yJmUWiYgX+aKxt+mVLmjxmubQFf2HRsqo892yL2nYty9c8J6G+Z6SN4yhTL95dgPEukZUyrhbvssK1+q2NhLC8d6u8sVP5IemcbVIPENVcoYvX6VZJQobrrUMYrSKmG1m6Kyi1kQVLLygE09tjpObOQLuhFe7ReoNpMw6CcQ9SCJKbUqUTnt9acpnzc+OgrgCpvIIGn5CGH/V0NaPT79gMGqIpnnr9mbFTyBnz2w7+L3ABTaqB8nS5A5+ZWbpzZzIlEOipMW2ZmQoPDWUQbKTR/f08gudgtg+rFUExjmPv8MCL+scnDvGNPa8VHpiMOT6pb9uJ9hx1tIM/HQhv/XQciQWkTQ/jYhpgw2w3obzEhRn0aDXZIS+Wlf851sG3eUuOyHQMBDzi6ZbhkbiSCYMh+aoGBD75LPzeq2EoV8UbJm8yKge820FM4iSP5tN0SU="
