sudo: required
language: node_js
env:
  global:
  - ECS_CLUSTER=pruebita-6
  - AWS_REGION=ue-east-2
  - secure: AKdtiRgDR2TR4jTP7hn8sPKa4LNWY6vbRwWnnzmC18eb5lFTSmLOj0yypzFebmwKY8No6WSnQThFXEx2rRBfGusiJSJpNbZS7A8b/AoWO54PudFHGfjLmen0EPGHUetvChDZEgE5IG5ZolV/bDIXGJ9mzpJm+tlfqPTanbWrP564UrU4dWutyqQx0i55R7AL9h0Ku07ct2U/zfivp0b3r5GDpHSxTBpoM1NGtvwZ11dKM6RYUxDJS0ivFjVZs7nz+BfjvBL+wQGF5P0mp0jtf4igSbkqodumlDZnjMWnmESJn9B3grMw3ZpxY/5Irf+C2rGf0mVeSlbvXy8n/VRLt7fl9WJ1MNG017kr8RVhiUL5pi0VcFLLgukhvHFwIpjWNv0mPihJk+jW9V19QKj4AXMelgbNvfCxLeJMg4hT95vr6igDoMDgMvWYpBesF4YIZwEWnCfzkEQRKhLK4w43VcyCmfmi14Rj1ju5a25b/VgQCrylQ2/tQSD7XAT4mjfOxgZ9ZBeYL4C2ZKy0uaaOBJZ9+tE3Z7YI5n5rd+vSB6tSwuPzmvouH0TU8hosR3K8kUQd/QDqkvEmz8UKUedCCI1Evaqqo/C+ROiXUczY/KU1YPThg9FGWii/LnLTTOOrNcVbw+lYBPzVF7UKqFG/11nltH5rCoOfpu0hynk4ySE=
  - secure: 3l9nc0+5OxM4sP95exUaj4M/wfPyZl0DeiRyZE6iKlJsslrL6r9TQoStf4t3Z4B+777doKCnT5AuJJnyI1+G7tX4PWSkhPXzikiXDw3ufCPNs12wRlTr4gQqPS9AuJcAwSlqE3z3N21UdgTLHe/8+Ki8VFJRdbzfMyjhB1xlPnd3YCraWhI2DSBFiWzpinHIhOy8alDJwi3dJJ9ijpGF1mDuFc7TwwjpAvpg3AtGXHok5YQcolg6rkvjTyRGSSlLVvGq67ia00jePhLsG/XICSWKHGIbQAM558wblncGTILW4dZyH1X5IgMqcHZtwcD4zJoBxWJkTvJS7Yj+ZLV/GJ79eoB9Kb+JgvJHs/A+V6zO8xs82YEkyWXIqc52LIjtVFglGUcjvkyCtVtSjLYRfqSxoqyhpM23s9dJBXPQ4SCLrIa0RzBY5GVWgMIQSugb/5lXgReeKAHhCwre3o15LmyRJh+5ZSjuOX71pgkD224lC+3+NX441hooUy/CHkz2yF8DMC0I1Eh/QrDIjWuJNgBQw/H5yD0UT5P7RLPQ9RClMDPAOIDNhBZXXA8YpdO1briOnPd00Jy4t+7TZ4UDJ6QJp5PibJZEmPXtZ2FzFA23ocPSH8rfdT3lOjiNZWojv8fRx9mKfSWYvCzXiybnKJAsVw0ai5wz9TB5ug49z/0=
services:
- docker
node_js:
- 8.11.3
script:
- npm run test
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- echo $AWS_ACCESS_KEY_ID
- echo $AWS_SECRET_ACCESS_KEY
- eval $(aws ecr get-login --no-include-email --region us-east-2)
- docker build -t express-hello .
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- export HELLO_IMAGE_VERSION=$TRAVIS_COMMIT
- node run generateDeployFile
- sudo curl -o ./ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- chmod +x ./ecs-cli
- "./ecs-cli compose down"
- "./ecs-cli compose up"
