sudo: required
language: node_js
env:
  global:
    secure: W6/JCyfWHABH3WIDucXjzTYlduR0BLbvED/J3c665BKP7S2O8I6JhajlRUEx1B5fyDOhCBs1SvNxshLAOmTfx6aF9Eq7+vkXBQu4St+B7jT8EwJB4Y0CWE7lFSZupz7c8CL2lb9K01Ay/7tHWhUzB10W8TYIJ3JAVWiO/HAb6jscT5p/EU0QGvwUcdk0ImSpIxKbc4iKqBOXImxpgr7D9vfKG+PvMOznNStxi/0VrVPZLJZxH34qIU9BiBUw+/RbiJV5Xxaf1E0f6esUT52rLhd7jz7QD/aB27+aqkZn08kfG7KMtV/yX0G2a/MDRdc9V/lvOEopWlqwVZY2x67cTgPx4sAF/vTAEnRuwdQJ6SgqrBSAo+lw4fyLPuUh0J0qH2rpG3qH5kHfZJ/e1CH8iyFip6wX/U1OAduZx4myLfQzZQ/A60irMX2AfD3hUTVAxa+33/zyxX92i/8MyXnpIU+qa1FC0aUOcap+cNinACUNh8+i+Nox5u54EvFzBaarAXulNy835sDC6AffMtCU15NdOrlKGTwjIQouGR4LChQWf6GR+vvxnxGPyaTeudC367zsusx3kN1vR6zIF/9V7aqggvbR+55lE66pGa85ZRv3qiNCrfSR3P36o12CkuqtWFQqlCoUfy8Mn640KuPZwi3nuhHHDb8EJ9h+ZHA4iKQ=
services:
- docker
node_js:
- 8.11.3
script:
- npm run test
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- echo $AWS_ACCESS_KEY_ID
- echo $AWS_SECRET_ACCESS_KEY
- eval $(aws ecr get-login --no-include-email --region us-east-2)
- docker build -t express-hello .
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker tag express-hello:latest 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:$TRAVIS_COMMIT
- docker push 412237081001.dkr.ecr.us-east-2.amazonaws.com/express-hello:latest
- export HELLO_IMAGE_VERSION=$TRAVIS_COMMIT
- node run generateDeployFile
- sudo curl -o ./ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- chmod +x ./ecs-cli
- "./ecs-cli compose down"
- "./ecs-cli compose up"
